export default {
    START_DASHBOARD_STATISTIC_POST:'START_DASHBOARD_DATA_POST',
    FINISH_DASHBOARD_STATISTIC_POST:'FINISH_DASHBOARD_DATA_POST',
    RECEIVE_DASHBOARD_STATISTIC:'RECEIVE_DASHBOARD_STATISTIC'
}