export default {
    START_DASHBOARD_STATISTIC_POST:'START_DASHBOARD_DATA_POST',
    FINISH_DASHBOARD_STATISTIC_POST:'FINISH_DASHBOARD_DATA_POST',
    RECEIVE_DASHBOARD_STATISTIC:'RECEIVE_DASHBOARD_STATISTIC',
    ADD_EMPTY_INSTOCK_ROW:'ADD_EMPTY_INSTOCK_ROW',
    REMOVE_INSTOCK_ROW:'REMOVE_INSTOCK_ROW',
    SAVE_INSTOCK_ROW_MODIFY:'SAVE_INSTOCK_ROW_MODIFY',
    SAVE_PRODUCT_CONSTRUCT_TABLE:'SAVE_PRODUCT_CONSTRUCT_TABLE',
    RESET_PRODUCT_CONSTRUCT_TABLE:'RESET_PRODUCT_CONSTRUCT_TABLE',
    SAVE_PREOUTSTOCK_PRODUCT_TABLE:'SAVE_PREOUTSTOCK_PRODUCT_TABLE',
    RESET_PREOUTSTOCK_PRODUCT_TABLE:'RESET_PREOUTSTOCK_PRODUCT_TABLE'
}